json.id post[:id]
json.title post[:title]
json.url post[:url]
json.points post[:points]
json.comments post[:comments]
json.author post[:author]
json.comments_url post[:comments_url]
json.source post[:source]